# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[secrets_scan]
  omit_keys = [
    "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY",
    "NEXT_PUBLIC_CLERK_SIGN_IN_URL",
    "NEXT_PUBLIC_CLERK_SIGN_UP_URL",
    "NEXT_PUBLIC_BACKEND_URL"
]